# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2daa0b55771b934fd4bab7c4e8aa55271a26a3ec2e8b9b2ddc77ddb9ed3e9a48394b10710e2c48d92f399cadc0f1505a0d3407e3f920db77667332184ceab571

test:
  secret_key_base: 41d66e802e56c5b2e8efbcd35aa0487c8ad7e1ebab8796cf442e7b7ffae332534b9b374f3c69fc905e2636a1ebeaa6ba1472f338e497b02c870a5c3e8700f846

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
